// autogenerated pch file for module: discretedata
#include <inviwo/core/common/inviwo.h>
#include <inviwo/core/common/inviwomodule.h>
#include <inviwo/core/datastructures/datatraits.h>
#include <inviwo/core/metadata/metadata.h>
#include <inviwo/core/metadata/metadataowner.h>
#include <inviwo/core/util/assertion.h>
#include <inviwo/core/util/formatdispatching.h>
#include <inviwo/core/util/glm.h>
