// autogenerated pch file for module: assimp
#include <array>
#include <ctime>
#include <inviwo/core/common/inviwo.h>
#include <inviwo/core/common/inviwomodule.h>
#include <inviwo/core/datastructures/buffer/bufferramprecision.h>
#include <inviwo/core/datastructures/geometry/mesh.h>
#include <inviwo/core/io/datareader.h>
#include <inviwo/core/io/datareaderexception.h>
#include <inviwo/core/util/exception.h>
#include <inviwo/core/util/logcentral.h>
#include <inviwo/core/util/stringconversion.h>
